apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.AccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.AccountName }}-cluster-role
rules:
  -
    apiGroups:
      - "*"
    resources:
      - "*"
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.AccountName }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.AccountName }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.AccountName }}
  namespace: {{ .Values.namespace }}