replicaCount: 1
namespace: default

dumperImage:
  repository: k8s.gcr.io/hyperkube-amd64
  tag: v1.14.8

pusherImage:
  repository: quay.io/coreos/awscli
  tag: master

rbac:
 AccountName: eksctl-upp-autosave-serviceaccount

